### ISSUE TITLE
Authentication and Authorization

### ISSUE THREAD

**Issue by bradenmacdonald** [open-craft/blockstore#32]
How will Blockstore authenticate and authorize requests? Authentication is not too hard, and we have existing solutions (signed JWTs from the LMS, etc.) but authorization gets really tricky. The main problem to solve is the complexity involved in courseware authorization decisions (authorization to view/learn content depends on a very complex intersection of user role, user affiliation, user course enrollment status, release dates, randomized content assignation / adaptive learning dynamic assignation, content groups, cohorts, etc.) and the sheer amount of corresponding data that must be consulted to make authorization decisions.

There are two solutions that I've been thinking about:

1. The simplest solution I'm aware of is to not allow most services to access Blockstore directly, and instead proxy requests through the LMS and/or Studio which can then apply appropriate permissions checks, using its knowledge of things like enrollments, cohorts, org-level permissions, etc. Then Blockstore doesn't need to worry about authentication at all. This is probably my default option due to its simplicity and that it requires very little additional work to implement.

2. The other interesting option I'm aware of is to have an independent authorization (micro)service, which stores most data it needs in memory and can provide blazing-fast yes/no answers to detailed questions about which users can do what. The model for this is Amazon's IAM, which supports incredibly complex policies at massive scale with minimal latency. The most interesting open source implementation of this that I've found is https://www.openpolicyagent.org/ which looks very promising, though I'm still unclear on whether or not there's any way to provide it with the required context data (enrollments, randomized content assignation, adaptive learning engine results, etc.) in real time (maintaining a single source of truth for those things) vs. having to push that data into it (duplicating data like enrollment data so that it now lives both in the LMS and in the Open Policy Agent cache) and deal with potential latency or inconsistent data. 

Other software related to option 2:
* [keto](https://github.com/ory/keto) is a "cloud native access control server" that uses Open Policy Agent. It previously was powered by [ladon](https://github.com/ory/ladon) which is like an open source implementation of IAM policies, but that was replaced with Open Policy Agent.
* [Mozilla doorman](https://github.com/mozilla/doorman) much simpler authorization microservice, probably not scalable to Open edX use cases

Thoughts? Other options?

**Comment by UmanShahzad** [comment]
The dedicated service path is certainly a long-term gain - it'll be a central place for authorization concerns, and that reduces complexity in understanding where and how authorization happens relative to it being sprinkled throughout several codebases - but don't underestimate the plumbing needed to get reliable service-to-service interaction! It's a single point of failure for all systems requiring auth, so besides just figuring out how it'd optimally *do* auth, a huge part will go into ensuring it's reliable and stores fully up-to-date (consistent) data across a cluster of these things.

Keto is written in Golang - that introduces a totally new dimension of work; presumably the edX ecosystem will end up with use cases that require a fork and then an upstreaming of those implementations; deployment and operations will be different from all the existing tooling based around Python; etc. For such a fundamental service it's probably good to roll your own to have full control over its feature set, performance characteristics, etc.

An alternative to both models is a hybrid - an auth service that can reach into other service's databases with read-only permissions to get its full intel for any auth request. It can use a library to do this, which can be installed in and used by edx-platform too, so that when you update it, it affects both without inconsistencies, and so you can always decide to back out of having a central auth server without rewriting everything.

**Comment by ormsbee** [comment]
@bradenmacdonald: I also vote for option 1, for the same reasons as you. Maybe later we can have LMS grant a token that gives you some kind of access to a single collection or something. But let's default to the simple thing for now.

**Comment by bradenmacdonald** [comment]
👍

**Comment by symbolist** [comment]
If I remember correctly it was mentioned in the last Arch hangout that the plan is not to go with a centralized authorization checks service because of availability concerns.

https://docs.google.com/presentation/d/10WX1YGzYPshgbVKFxf9hWfGdXOYU9xL6iTbDRqq6u5I/edit#slide=id.g4e2e0ef739_0_174

Agree that 1 makes sense for calls that involve the XBlock Runtime. But it is likely not going to work for anything that involves ElasticCache. It should be simpler though since most permission dimensions will not apply to the data in there but I am waiting for the LX moderation requirements to form a better/detailed opinion.
